language: python
python:
  - '2.7.11'
  - '3.5.1'
cache: pip
env:
    matrix:
        - DJANGO="Django<1.9,>=1.8"
        - DJANGO="Django<1.10,>=1.9"
install:
  - pip install $DJANGO
  - pip install -r x_robots_tag_middleware_demo/requirements_ci.txt
script: coverage run --source=x_robots_tag_middleware,x_robots_tag_middleware_demo --rcfile=devscripts/checkers/coveragerc manage.py test
sudo: false
after_success: coveralls
deploy:
  provider: pypi
  upload_docs: no
  user: Tim.White
  password:
    secure: liX8rWN6UtxQC+HKoUdn6ht6QKpJRhvpNJuBFcNqLIIeepolW0EgB+FpZ528u2Usw7mr6DncH0ZTkPgShp4ZgCdRjtlFPg3dCyQUShHKiZ2vom/jMbW2yvkjpx/d/nVCDxv0Sxfv8ERdIiJHb84fTg9QhoF+4nvR6rEu9+g6ZO7ecnQCDN9ReZ3Fgt8Zt5gBudeQE245lN7mlwliGXsR7WiDW0zfU0AcrIq/YB50iPuArvaAS+CUiSMqKxlI0TyfpP22vVdZ1k4kjnoUdeKP7jFrilnJCgAHpuAShwpyQxAaOi572ZOuyLVYn1YxlEwgKSzXYlUTZ1rmKraoV2hlng0Hv9kUbDxmOr0d55ZVzwWDlhKax1fdTDQKRqM22ntypAyoO8E92ujfTa8d05riYQEUXC9wJKN0BucZnOvTKVU1PNSL2glh/Wkl9tIwVZkKpOYUSBoVOsh1zC8ToizrJ0sDGuio/Kh8wSzOmEYuihwXtsaRSJiR2Wc9IEqZyZUTeOkbCvFbROnxUaebHMhGBTTWKgRQq9nJmPcEDhoAH8bE0tMMdsvndiNikaMOMxowo0AXI6Tf7nI/uoPQf9AI+I58U26EyxcLcyAlUxfy0dI1Cst1UuQDRt0ZRT2e7EL5Xiri4gaUfod1L4D6F/CrzVJinjmWUUcqCv7VOgQyOMU=
  on:
    repo: cyface/django-x-robots-tag-middleware
